[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino

; 1. Cấu hình tốc độ nạp code và monitor (Mở Serial Monitor ở mức 115200)
monitor_speed = 115200
upload_speed = 921600

; 2. Cấu hình cho 16MB Flash
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; 3. Cấu hình bật 8MB PSRAM 
board_build.arduino.memory_type = qio_opi
build_flags = 
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
    -D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

; 4. Cấu hình một số thư viện
lib_deps =
 	 ; --- TẢI THƯ VIỆN ADAFRUIT ---
	adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
	adafruit/Adafruit GFX Library @ ^1.11.9
	 ; thư viện RFID
	miguelbalboa/MFRC522 @ ^1.4.11
	 ; thư viện động cơ servo 
	madhephaestus/ESP32Servo @ ^3.0.5	
	; thư viện DHT11 sensor
	adafruit/DHT sensor library@^1.4.7
	; thư viện LED RGB
	adafruit/Adafruit NeoPixel @ ^1.12.0
	; thư viện âm thanh 
	https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
	; thư viện cảm biến ánh sáng
	claws/BH1750 @ ^1.3.0
	; thư viện wifi
	tzapu/WiFiManager
	; thư viện app up data
	blynkkk/Blynk